### ISSUE TITLE
/is schematic create error

### ISSUE THREAD

**Issue by nurdism** [DevOnTheRocks/SkyClaims#116]
This seems to be a *sponge* error, but not sure how to submit a proper bug report as I know nothing about the sponge eco system.

### Version:
- **Sponge:** spongeforge 1.12.2-2838 7.1.7 RC3902
- **SkyClaims:** SkyClaims 0.28.0-S7.1 PR3
- **GriefPrevention:** griefprevention 1.12.2 4.3.0.692
- **Permissions:** LuckPerms 4.4.28

### Expected Behavior:
`/is schematic create botania` to create schematic

### Actual Behavior:
Console Error: 
```
[16:36:05] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'is schematic create botania' for source GCEntityPlayerMP['Nurdism'/356, l='world', x=1053.59, y=86.00, z=749.52]: null
java.lang.IllegalStateException: null
at com.google.common.base.Preconditions.checkState(Preconditions.java:429) ~[minecraft_server.1.12.2.jar:?]
at org.spongepowered.common.entity.SpongeEntityArchetypeBuilder.build(SpongeEntityArchetypeBuilder.java:171) ~[SpongeEntityArchetypeBuilder.class:1.12.2-2838-7.1.7-RC3902]
at net.minecraft.entity.Entity.createArchetype(Entity.java:5048) ~[vg.class:?]
at org.spongepowered.common.world.extent.DefaultedExtent.createArchetypeVolume(DefaultedExtent.java:202) ~[DefaultedExtent.class:1.12.2-2838-7.1.7-RC3902]
at net.mohron.skyclaims.command.schematic.CommandSchematicCreate.execute(CommandSchematicCreate.java:68) ~[CommandSchematicCreate.class:?]
at net.mohron.skyclaims.command.CommandBase$PlayerCommand.execute(CommandBase.java:88) ~[CommandBase$PlayerCommand.class:?]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.1.7-RC3902]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.1.7-RC3902]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.1.7-RC3902]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2838-7.1.7-RC3902]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:338) [SpongeCommandManager.class:1.12.2-2838-7.1.7-RC3902]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) [PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3902]
at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlb000(SourceFile:540) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3902]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4716) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
### Steps To Reproduce:
This does not happen in a normal forge server with no mods:
Using Project Ozone 3 modpack
Creating default schematic for botania skyblock
Selected island and ran command, error is produced

I have a feeling its due to GCEntityPlayerMP from Galacticraft. But ¯\\_(ツ)_/¯

**Comment by Mohron** [comment]
Yeah, this would be a SpongeForge bug. Somewhat recently Sponge added entity support to schematics and I remember briefly that there was a bug caused by them not filtering out player entities. Since GalacticCraft overrides the base forge player, it's likely not being filtered out by sponge, causing the error you're experiencing.

You could try making the schematic without GalacticCraft installed to work around this issue in the meantime.

**Comment by nurdism** [comment]
yeah that's what I ended up doing and it works fine
