### ISSUE TITLE
not empty the backpack

### ISSUE THREAD

**Issue by yahinstudio** [DevOnTheRocks/SkyClaims#122]
I would like to ask how to configure so that players will not empty the backpack when creating an empty island, because I want to replace the plot with the empty island.

**Comment by Mohron** [comment]
By backpack do you mean inventory? If so, take a look at these permissions:
https://github.com/DevOnTheRocks/SkyClaims/blob/sponge/api-7/src/main/java/net/mohron/skyclaims/permissions/Permissions.java#L47-L56

If not, github isn't really the place for support/asking questions. If you're able, I recommend you join the [Discord](https://discord.gg/EkVQycV) server to ask any further questions about SkyClaims.

**Comment by yahinstudio** [comment]
Yes.Is it enough to grant the player the above permissions?

**Comment by yahinstudio** [comment]
I have another question, what should I do if I use is tp <player> to teleport to the player's empty island?
```
[13:30:44] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'is tp AML' for source EntityPlayerMP['yahin'/543111, l='plot', x=51.34, y=65.50, z=105.78]: java.util.UUID cannot be cast to net.mohron.skyclaims.world.Island
java.lang.ClassCastException: java.util.UUID cannot be cast to net.mohron.skyclaims.world.Island
        at net.mohron.skyclaims.command.user.CommandSpawn.execute(CommandSpawn.java:65) ~[CommandSpawn.class:?]
        at net.mohron.skyclaims.command.CommandBase$PlayerCommand.execute(CommandBase.java:89) ~[CommandBase$PlayerCommand.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.1.7-RC3899]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.1.7-RC3899]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2838-7.1.7-RC3899]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:338) [SpongeCommandManager.class:1.12.2-2838-7.1.7-RC3899]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) [PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3899]
        at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zkp000(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3899]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjd000(MinecraftServer.java:4716) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]```

**Comment by Mohron** [comment]
I don't understand what you are asking.

Based on the stack trace though, it doesn't appear that you are using the latest SkyClaims release. Please update to the latest release and try again before reporting any issues/errors.

**Comment by Mohron** [comment]
Closing due to no response
