### ISSUE TITLE
/is tp not working every time

### ISSUE THREAD

**Issue by TheNickoos** [DevOnTheRocks/SkyClaims#123]
```
> [15:44:10] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'is tp Brxtor' for source EntityPlayerMP['lulu_mania'/22221, l='world', x=1278.61, y=65.00, z=1278.64]: java.util.UUID cannot be cast to net.mohron.skyclaims.world.Island
java.lang.ClassCastException: java.util.UUID cannot be cast to net.mohron.skyclaims.world.Island
at net.mohron.skyclaims.command.user.CommandSpawn.execute(CommandSpawn.java:65) ~[CommandSpawn.class:?]
at net.mohron.skyclaims.command.CommandBase$PlayerCommand.execute(CommandBase.java:89) ~[CommandBase$PlayerCommand.class:?]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.1.8]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:338) [SpongeCommandManager.class:1.12.2-2838-7.1.8]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:218) [PacketPhaseUtil.class:1.12.2-2838-7.1.8]
at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlj000(SourceFile:540) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.8]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:4716) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

### Version:

- **Sponge:** spongeforge-1.12.2-2838-7.1.9-RC3980
- **SkyClaims:** SkyClaims-0.29.0-S7.1-BETA-plugin
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.692
- **Permissions:** LuckPerms-Sponge-5.0.39

### Expected Behavior:

/is tp seem not working

**Comment by Mohron** [comment]
Update to 29.1
