### ISSUE TITLE
Can't create islands

### ISSUE THREAD

**Issue by Druwan-ctrl** [DevOnTheRocks/SkyClaims#137]
I'm trying to create an island, but it only produces an error:

```
 [Sponge]: Error occurred while executing command 'is create prova' for source EntityPlayerMP['Druwan'/6884, l='world', x=287.88, y=75.00, z=860.52]: com.griefdefender.api.claim.ClaimResult.getClaim()Ljava/util/Optional;
java.lang.NoSuchMethodError: com.griefdefender.api.claim.ClaimResult.getClaim()Ljava/util/Optional;
        at net.mohron.skyclaims.util.ClaimUtil.createSpawnClaim(ClaimUtil.java:145) ~[ClaimUtil.class:?]
        at net.mohron.skyclaims.world.region.SpiralRegionPattern.nextRegion(SpiralRegionPattern.java:88) ~[SpiralRegionPattern.class:?]
        at net.mohron.skyclaims.world.Island.<init>(Island.java:96) ~[Island.class:?]
        at net.mohron.skyclaims.command.user.CommandCreate.createIsland(CommandCreate.java:92) ~[CommandCreate.class:?]
        at net.mohron.skyclaims.command.user.CommandCreate.execute(CommandCreate.java:72) ~[CommandCreate.class:?]
        at net.mohron.skyclaims.command.CommandBase$PlayerCommand.execute(CommandBase.java:89) ~[CommandBase$PlayerCommand.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.4.2]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.4.2]
        at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.4.2]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.4.2]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.4.2]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zli000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:325) [SpongeImplHooks.class:1.12.2-2838-7.4.2]
        at net.minecraft.server.MinecraftServer.redirect$zjm000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

### Version:

- **Sponge:** spongeforge-1.12.2-2838-7.4.2
- **SkyClaims:** SkyClaims-0.31.0-S7.13-GRIEF-DEFENDER-SNAPSHOT-plugin
- **GriefPrevention:** griefdefender-sponge-2.0.4
- **Permissions:** LuckPerms-Sponge-5.2.76

### Steps To Reproduce:

Setting up everything, /is create grass, error thrown

**Comment by Mohron** [comment]
The version of SkyClaims you were using does not support GD 2.X. Please use the latest release, [`0.32.1`](https://github.com/DevOnTheRocks/SkyClaims/releases/tag/0.32.1-GRIEF-DEFENDER-2) as of now, with GD 2.X

**Comment by Druwan-ctrl** [comment]
Thanks for updating!
