### ISSUE TITLE
an error...

### ISSUE THREAD

**Issue by subtank** [DevOnTheRocks/SkyClaims#15]
when i try to create a new island,an error occur 
error occurred while executing command: could not initialize class net.mohron.skyclaims.util.islandutil

**Comment by Mohron** [comment]
I need more details in order to help you. What version of SkyClaims, GriefPrevention, & SpongeForge are you using? If they're not the latest, update and try again. If you still get an error, copy your fml-server-latest log into a paste or gist.

**Comment by subtank** [comment]
all plugin are the latest vision

**Comment by subtank** [comment]
all plugin are the latest vision,here are the fml-server-latest log

```[19:26:07] [Server thread/INFO] [io.github.hsyyid.essentialcmds/]: [subtank] executed command is create 1
[19:26:07] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'is create 1' for source EntityPlayerMP['subtank'/264, l='let's rock!', x=289.68, y=204.00, z=278.64]: null
java.lang.ExceptionInInitializerError
	at net.mohron.skyclaims.command.CommandCreate.execute(CommandCreate.java:51) ~[CommandCreate.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at net.mohron.skyclaims.util.IslandUtil.<clinit>(IslandUtil.java:15) ~[IslandUtil.class:?]
	... 21 more
[19:26:10] [Server thread/INFO] [io.github.hsyyid.essentialcmds/]: [subtank] executed command is create
[19:26:10] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'is create' for source EntityPlayerMP['subtank'/264, l='let's rock!', x=289.68, y=204.00, z=278.64]: Could not initialize class net.mohron.skyclaims.util.IslandUtil
java.lang.NoClassDefFoundError: Could not initialize class net.mohron.skyclaims.util.IslandUtil
	at net.mohron.skyclaims.command.CommandCreate.execute(CommandCreate.java:51) ~[CommandCreate.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[19:26:21] [HikariPool-2 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-2 - Pool stats (total=3, active=0, idle=3, waiting=0)
[19:26:23] [Server thread/INFO] [io.github.hsyyid.essentialcmds/]: [subtank] executed command is create
[19:26:23] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'is create' for source EntityPlayerMP['subtank'/264, l='let's rock!', x=288.26, y=204.00, z=276.70]: Could not initialize class net.mohron.skyclaims.util.IslandUtil
java.lang.NoClassDefFoundError: Could not initialize class net.mohron.skyclaims.util.IslandUtil
	at net.mohron.skyclaims.command.CommandCreate.execute(CommandCreate.java:51) ~[CommandCreate.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2171-5.1.0-BETA-2000]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Mohron** [comment]
@subtank I need you to list all the version you are using, not latest! Also, please pastebin/gist a server log, not just the error like I originally asked.

**Comment by subtank** [comment]
here are my plugin and all server log

**Comment by Mohron** [comment]
@subtank There's nothing in your message.

**Comment by subtank** [comment]
why couldn't uoload the zip file? hold on second.i just try another way

**Comment by Mohron** [comment]
@subtank Use pastebin or gist for the log and just type out your plugin/mod versions

**Comment by subtank** [comment]
![image](https://cloud.githubusercontent.com/assets/19743209/22047399/ca854d18-dd61-11e6-8828-6c0c04930707.png)

[fml-server-latest.txt](https://github.com/DevOnTheRocks/SkyClaims/files/712814/fml-server-latest.txt)

**Comment by subtank** [comment]
is that ok?

**Comment by Mohron** [comment]
@subtank You are using a severely outdated Sponge Forge Build. That causes GP to never load which is what caused your error.
https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2

**Comment by adpking** [comment]
Please check the dependencies of all the mods before posting it as a coding issue.

**Comment by subtank** [comment]
thanks
