### ISSUE TITLE
error occurred while executing command: null

### ISSUE THREAD

**Issue by Westus** [DevOnTheRocks/SkyClaims#21]
![2017-02-12_19-14-45](https://cloud.githubusercontent.com/assets/4818769/22899257/3c3c4f4a-f23b-11e6-9ef4-19938ceaf70a.png)

error appears when trying to create an island:
```
[22:21:54] [Server thread/DEBUG] [skyclaims/]: Region Pattern: [(0,0),(1,0),(1,1),(0,1),]
[22:21:54] [Server thread/DEBUG] [skyclaims/]: Coordinates length: 4
[22:21:54] [Server thread/DEBUG] [skyclaims/]: Checking for next region out of 4 points with 1 spawn regions.
[22:21:54] [Server thread/DEBUG] [skyclaims/]: Skipping (0, 0) for spawn
[22:21:54] [Server thread/DEBUG] [skyclaims/]: Checking region (1, 0) for island
[22:21:54] [Server thread/DEBUG] [skyclaims/]: Creating WestusBox's claim in region (1, 0). Claimed from 639x, 127z - 895x, 383z.
[22:21:54] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'is create' for source EntityPlayerMP['WestusBox'/0, l='world', x=4.53, y=69.00, z=7.38]: null
java.lang.NullPointerException
	at net.mohron.skyclaims.database.Database.saveIsland(Database.java:110) ~[Database.class:?]
	at net.mohron.skyclaims.world.Island.save(Island.java:271) ~[Island.class:?]
	at net.mohron.skyclaims.world.Island.<init>(Island.java:67) ~[Island.class:?]
	at net.mohron.skyclaims.command.user.CommandCreate.execute(CommandCreate.java:57) ~[CommandCreate.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295) ~[SpongeCommandManager.class:1.10.2-2221-5.1.0-BETA-2142]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:156) [CauseTracker.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2221-5.1.0-BETA-2142]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[22:21:54] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task skyclaims-S-4 owned by Plugin{id=skyclaims, name=SkyClaims, version=1.0.0-beta16, description=SkyClaims is an Island Management plugin that integrates with GriefPrevention., authors=[Mohron, Cossacksman], source=/home/easet/multicraft/servers/FTB_SkyFactory_3_1102/./mods/plugins/skyclaims-1.0.0-beta16.jar}, but an error occured.
java.lang.NullPointerException
	at net.mohron.skyclaims.database.Database.saveIsland(Database.java:110) ~[Database.class:?]
	at net.mohron.skyclaims.world.Island.save(Island.java:271) ~[Island.class:?]
	at net.mohron.skyclaims.world.Island.setSpawn(Island.java:216) ~[Island.class:?]
	at net.mohron.skyclaims.world.GenerateIslandTask.run(GenerateIslandTask.java:75) ~[GenerateIslandTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.10.2-2221-5.1.0-BETA-2142]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_111]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2221-5.1.0-BETA-2142]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271) [SpongeMod.class:1.10.2-2221-5.1.0-BETA-2142]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_30_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

[fml-server-latest.txt](https://github.com/DevOnTheRocks/SkyClaims/files/772182/fml-server-latest.txt)

**Comment by Mohron** [comment]
@Westus are you trying to use MySQL instead of SQLite?

**Comment by Westus** [comment]
@Mohron Here are my settings:
```
Config-Version=1
Misc {
    # Commands to run on island creation and reset.
    Create-Commands=[]
    # Automatically create an island for a player on join.
    Island-on-Join=false
    # Commands to run on island resets only.
    Reset-Commands=[]
}
Permission {
    # Enable permission checking for the Biome Type Argument.
    Separate-BiomeType-Permissions=false
    # Enable permission checking for the Schematic Argument.
    Separate-Schematic-Permissions=false
    # Enable permission checking for the Target Argument.
    Separate-Target-Permissions=false
}
Storage {
    # The location to store SkyClaims data. Default: *CONFIG*/data
    Location="*CONFIG*\\data"
    MySQL {
        Location=localhost
        Name=skyclaims
        Password=skyclaims
        Port=3306
        Table-Prefix=""
        Username=skyclaims
    }
    SQLite {
        # Deprecated. Do not use!
        Location=".\\"
        # Deprecated. Do not use!
        Name=skyclaims
    }
    # The type of data storage to use. Supports [SQLite, MySQL]
    Type=SQLite
}
World {
    # Height to build islands at. Default: 72
    Island-Height=72
    # Name of the world to manage islands in. Default: world
    SkyClaims-World=world
    # The height & width of regions to reserve for Spawn. Default: 1
    Spawn-Regions=1
}
```

**Comment by Mohron** [comment]
@Westus Did you by chance initialize SkyClaims on Windows and copy it with the config to Linux/Unix?

**Comment by Westus** [comment]
@Mohron Yes. skyclaims.conf I deleted on the server and now everything worked correctly.

**Comment by Mohron** [comment]
Thanks for verifying! Will be fixed in the next version I release.
