### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by qsxzaqq** [DevOnTheRocks/SkyClaims#80]
[21:42:52] [Server thread/ERROR] [Sponge]: Could not pass LoadWorldEvent$Impl to Plugin{id=skyclaims, name=SkyClaims, version=0.26.0-S7.0-BETA, description=SkyClaims is an Island Management plugin that integrates with GriefPrevention., authors=[Mohron, Cossacksman], source=C:\Users\Administrator\Desktop\Sponge1.10.2\mods\SkyClaims-0.26.0-S7.0-BETA.jar}
java.lang.NoSuchMethodError: me.ryanhamshire.griefprevention.api.claim.Claim.setPermission(Lorg/spongepowered/api/service/permission/Subject;Lme/ryanhamshire/griefprevention/api/claim/ClaimFlag;Ljava/lang/String;Lorg/spongepowered/api/util/Tristate;)Ljava/util/concurrent/CompletableFuture;
        at net.mohron.skyclaims.listener.WorldLoadHandler.lambda$onWorldLoad$1(WorldLoadHandler.java:62) ~[WorldLoadHandler.class:?]
        at java.util.Map.forEach(Unknown Source) ~[?:1.8.0_131]
        at net.mohron.skyclaims.listener.WorldLoadHandler.onWorldLoad(WorldLoadHandler.java:60) ~[WorldLoadHandler.class:?]
        at org.spongepowered.common.event.listener.LoadWorldEventListener_WorldLoadHandler_onWorldLoad166.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:817) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2698]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:764) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2698]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by phit** [comment]
Please use the provided issue template. The log you provided does not give enough information to debug your issue.

**Comment by phit** [comment]
You are using skyclaims for 1.12.2, while your server is running 1.10.2, switch to the correct version.
https://ore.spongepowered.org/Mohron/SkyClaims/versions/0.26.0-S5.1-BETA
