### ISSUE TITLE
Error when executing island deletion

### ISSUE THREAD

**Issue by yyeerai** [DevOnTheRocks/SkyClaims#85]
### Version:

- **Sponge:**  
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-dfc5c4a
    SpongeForge: 1.12.2-2555-7.1.0-BETA-2844
    Minecraft Forge: 14.23.1.2602

- **SkyClaims:** SkyClaims-0.27.0-S7.0-BETA.jar 
- **GriefPrevention:**  4.30. 
- **Permissions:**  luckperms

### Actual Behavior:

```
`[16:09:08] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task skyclaims-S-11 owned by Plugin{id=skyclaims, name=SkyClaims, version=0.27.0-S7.0-BETA, description=SkyClaims is an Island Management plugin that integrates with GriefPrevention., authors=[Mohron, Cossacksman], source=/home/mc/island/mods/SkyClaims-0.27.0-S7.0-BETA.jar}, but an error occured.
java.lang.UnsupportedOperationException: This is an internal method not intended for use with Players as it causes the player to be placed into an undefined state. Consider putting them through the normal death process instead.
        at net.minecraft.entity.player.EntityPlayerMP.remove(EntityPlayerMP.java:4746) ~[oq.class:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_151]
        at net.mohron.skyclaims.world.RegenerateRegionTask.lambda$0(RegenerateRegionTask.java:86) ~[RegenerateRegionTask.class:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_151]
        at net.mohron.skyclaims.world.RegenerateRegionTask.run(RegenerateRegionTask.java:67) ~[RegenerateRegionTask.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2844]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_151]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2555-7.1.0-BETA-2844]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:269) [SpongeMod.class:1.12.2-2555-7.1.0-BETA-2844]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_81_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Mohron** [comment]
You somehow had a player on the Island when delete was run. Either the spawn you have set in the config is not safe or they tp'd there manually. Either way this shouldn't happen in normal circumstances.

**Comment by Mohron** [comment]
If you address whatever situation caused a player to be in the area during the wiping process, you won't see this again. Nonetheless I made a change to ensure it doesn't happen in the future but I won't be making a special release for this fix.
